server:
  port: 10086
spring:
  application:
    name: ly-registry
  rabbitmq:
    host: 192.168.5.125
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false
    register-with-eureka: false
