server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: /leyou
    password: leyou
    host: 192.168.5.125

leyou:
  sms:
    accessKeyId: LTAIR23G84ET9J4O
    accessKeySecret: IFzXpT1BFAiIvIaESmB8ECRsSVETRm
    signName: 三方录
    verifyCodeTemplate: SMS_157095058
